apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.backend.port }}
          resources:
            requests:
              memory: {{ .Values.backend.resources.requests.memory | quote }}
              cpu: {{ .Values.backend.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.backend.resources.limits.memory | quote }}
              cpu: {{ .Values.backend.resources.limits.cpu | quote }}
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: code-reviewer-secrets
                  key: GROQ_API_KEY
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: code-reviewer-secrets
                  key: FRONTEND_URL