apiVersion: v1
kind: Secret
metadata:
  name: code-reviewer-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  GROQ_API_KEY: {{ .Values.secret.groqApiKey }}
  FRONTEND_URL: {{ .Values.secret.frontendUrl }}