backend:
  image: code-reviewer-backend:latest
  replicas: 2
  port: 8000
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

frontend:
  image: code-reviewer-frontend:latest
  replicas: 2
  port: 80
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"

namespace: code-reviewer

secret:
  groqApiKey: ""
  frontendUrl: "http://localhost:3000"