name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: arijhajji/code-reviewer-backend:${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ../code-reviewer-ui
          push: true
          tags: arijhajji/code-reviewer-frontend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Deploy with Helm
        run: |
          helm upgrade --install code-reviewer ./helm/code-reviewer \
            --set backend.image=arijhajji/code-reviewer-backend:${{ github.sha }} \
            --set frontend.image=arijhajji/code-reviewer-frontend:${{ github.sha }} \
            --set secret.groqApiKey=${{ secrets.GROQ_API_KEY }} \
            --set secret.frontendUrl=http://localhost:3000